"Air": "Service:  Air"
"Air Force": "Service:  Air Force"
"Air Force Reserve": "Service:  Air Force Reserve"
"Air National Guard": "Service:  Air National Guard"
"Army": "Service:  Army"
"Army National Guard": "Service:  Army National Guard"
"Army Reserve": "Service:  Army Reserve"
"Coast": "Service:  Coast"
"Coast Guard": "Service:  Coast Guard"
"Coast Guard Reserve": "Service:  Coast Guard Reserve"
"Marine": "Service:  Marine"
"Marine Corps": "Service:  Marine Corps"
"Marine Corps Reserve": "Service:  Marine Corps Reserve"
"Navy": "Service:  Navy"
"Navy Reserve": "Service:  Navy Reserve"
